name: Build
on: [push, workflow_dispatch]

env:
  IMAGE: ghcr.io/dellelce/gpaw-base

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Mkit GPAW
        run: docker build -t $IMAGE .
      - name: GPAW check version
        run: |
              GPAW_VERSION=$(docker run --rm $IMAGE  /app/gpaw/bin/gpaw --version | awk -F- ' NR == 1 { print $1; } ')
              echo "GPAW_VERSION=$GPAW_VERSION" >> $GITHUB_ENV
      - name: Add tag & push
        run: docker tag $IMAGE $IMAGE:$GPAW_VERSION && docker push $IMAGE:$GPAW_VERSION && docker push $IMAGE
